name: 'Pull Request Linter'
description: 'An action to lint pull request titles'
inputs:
  title-regex:
    description: 'Regex used to lint pull request title'
    required: true
    default: '.*'
runs:
  using: 'node12'
  main: 'index.js'
