name: Pull Request Linter

on:
  pull_request:
    types: [opened,closed]

jobs:
  pr_lint_job:
    runs-on: ubuntu-latest
    name: A job to lint pull requests
    steps:
    - name: Action Step
      id: prlint
      uses: Samuel1989/pull-request-linter@master
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
