name: Pull Request Linter

on:
  pull_request:
    types: [opened,edited,reopened,synchronize]

jobs:
  pr_lint_job:
    runs-on: ubuntu-latest
    name: A job to lint pull requests
    steps:
    - name: Action Step
      id: prlint
      uses: Samuel1989/pull-request-linter@master
      with:
        title-regex: '^(hr|engage|recruit|core|pay|work|perform|learn|analytics)\/(feature|fix)\/*(.+)$'
        title-failed-comment: 'Incorrect title format, regex for correct format is %titleRegex%.'
        body-regex: '^\*\*TASK ID\*\*\n\s-\s\d+\n\n\*\*DESCRIPTION\*\*\n\s-\s(.+)\n\n\*\*RESOLUTION\*\*\n\s-\s(.+)\n\n\*\*NEW\/CHANGED CONFIG ELEMENT \(YES\/NO\)\*\*\n\s-\s(YES|NO)$'
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        label-text: "Testing labels"
