name: Pull Request Linter

on:
  pull_request:
    types: [opened,edited,reopened,synchronize]

jobs:
  pr_lint_job:
    runs-on: ubuntu-latest
    name: A job to lint pull requests
    steps:
    - name: Action Step
      id: PRLinter
      uses: Samuel1989/action-test@master
      with:
        title-regex: '^(hr|engage|recruit|core|pay|work|perform|learn|analytics)\/(feature|fix)\/*(.+)$'
        body-regex: '\*\*TASK ID\*\*\n\s-\s\d+\n\n\*\*DESCRIPTION\*\*\n\s-\s(.+)\n\n\*\*RESOLUTION\*\*\n\s-\s(.+)\n\n\*\*NEW\/CHANGED CONFIG ELEMENT \(YES\/NO\)\*\*\n\s-\s(YES|NO)'
        github-token: "${{ secrets.GITHUB_TOKEN }}"
